Mapping runs with GNU parallel. Added options --max-jobs and --dryrun. Deleted option --xml.

diff --git a/mapping b/mapping
--- a/mapping
+++ b/mapping
@@ -18,7 +18,7 @@
 # REVISION: ---
 #===============================================================================
 
-CODE=$(basename "$0")                                           # Executable name
+export CODE=$(basename "$0")                                           # Executable name
 SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"   # Directory of this script
 USAGE="Usage:
 
@@ -41,8 +41,66 @@ KEYWORD ARGUMENTS
 
 -z|--zip                    Perform comparison on zipped files using zcmp.
 
---xml-output                Produce xml output.
+-n|--max-jobs   N           Set the maximum number of jobs that will
+                            be run in parallel by GNU parallel
+                            (default is 20)
+
+--dryrun                    Show what commands will be run without running them.
 "
+
+
+
+#######################################################################
+#######################################################################
+#                                                                     #
+#                           FUNCTIONS                                 #
+#                                                                     #
+#######################################################################
+#######################################################################
+mapping_foo (){
+#=== FUNCTION =========================================================
+# NAME: mapping_foo
+# DESCRIPTION: Run NJOY calculation for a given ENDF-6 file using 
+#              "run-njoy" script.
+#              Use option --wdir to run the calculation in a subfolder
+#              with the same name as the basename of the ENDF-6 file.
+#              e.g. if the name of the file is "1-H-1g.jeff33", "run-njoy"
+#                   will be run in relative folder "./1-H-1g.jeff33/".
+#              Use option --aceonly only if set.
+#              Send stdout to /dev/null to avoid overlapping the stdout
+#              of different NJOY parallel runs.
+# PARAMETER 1: ENDF/6 file (absolute path)
+#======================================================================
+#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+# Reconvert exported strings DIRS, LIBS and VERS into arrays.
+#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+DIRS_ARRAY=($DIRS_STRING)
+LIBS_ARRAY=($LIBS_STRING)
+VERS_ARRAY=($VERS_STRING)
+CHUNK="$1"
+CLIB="$2"
+CVER="$3"
+NAME="$(basename $CHUNK)"
+MAT="$(echo $NAME | cut -c1-4 | sed 's/^0*//')"
+MF="$(echo $NAME | cut -c5-6 | sed 's/^0*//')"
+MT="$(echo $NAME | cut -c7-9 | sed 's/^0*//')"
+for i in $(seq 0 $((${#DIRS_ARRAY[@]}-1)))
+do
+   OLD="${DIRS_ARRAY[$i]}/$(basename $CHUNK)"
+   if [[ -s $OLD ]]
+   then
+      [[ -z $ZIP ]] && CMD="cmp" || CMD="zcmp"
+      if $CMD --silent $OLD $CHUNK
+      then
+         printf "%s,%s,%s,%s,%s,%s,%s\n" "$CLIB" "$CVER" "$MAT" "$MF" "$MT" "${LIBS_ARRAY[$i]}" "${VERS_ARRAY[$i]}"
+         break
+      fi
+   fi
+done
+}
+
+function join_by { local IFS="$1"; shift; echo "$*"; }
+
 
 
 
@@ -63,13 +121,17 @@ case $key in
     exit 0
     ;;
     -z|--zip)
-    ZIP="--zip"
+    export ZIP="--zip"
     shift # past argument
     ;;
-    --xml-output)
-    XML="$2"
+    -n|--max-jobs)
+    NJOBS="$2"
     shift # past argument
     shift # past value
+    ;;
+    --dryrun)
+    DRYRUN="--dryrun"
+    shift # past argument
     ;;
     *)    # unknown option
     POSITIONAL+=("$1") # save it in an array for later
@@ -114,17 +176,35 @@ done
 # Skip lines starting with # symbol.
 #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 [[ -s "$DIRLIST" ]] || { >&2 echo -e "ERROR: no file called '$DIRLIST'"; exit 1; }
-DIRS=($( awk '/^[^\#]/ {print $1}' $DIRLIST ))
-LIBS=($( awk '/^[^\#]/ {print $2}' $DIRLIST ))
-VERS=($( awk '/^[^\#]/ {print $3}' $DIRLIST ))
-NDIRS=${#DIRS[@]}
+DIRS_ARRAY=($( awk '/^[^\#]/ {print $1}' $DIRLIST ))
+LIBS_ARRAY=($( awk '/^[^\#]/ {print $2}' $DIRLIST ))
+VERS_ARRAY=($( awk '/^[^\#]/ {print $3}' $DIRLIST ))
+NDIRS=${#DIRS_ARRAY[@]}
 [[ $NDIRS -eq 0 ]] && {>&2 echo -e "ERROR: no directory was given.";exit 1;}
-[[ $NDIRS -ne ${#LIBS[@]} ]] && { >&2 echo -e "ERROR: first and second columns of file '$DIRLIST' have different length."; exit 1; }
-[[ $NDIRS -ne ${#VERS[@]} ]] && { >&2 echo -e "ERROR: first and third columns of file '$DIRLIST' have different length."; exit 1; }
-for DIR in ${DIRS[@]}
+[[ $NDIRS -ne ${#LIBS_ARRAY[@]} ]] && { >&2 echo -e "ERROR: first and second columns of file '$DIRLIST' have different length."; exit 1; }
+[[ $NDIRS -ne ${#VERS_ARRAY[@]} ]] && { >&2 echo -e "ERROR: first and third columns of file '$DIRLIST' have different length."; exit 1; }
+for DIR in ${DIRS_ARRAY[@]}
 do
    [[ -d "$DIR" ]] || { >&2 echo -e "ERROR: no directory called '$DIR'"; exit 1; }
 done
+#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+# Reconvert arrays to strings since we cannot export arrays
+# in bash.
+#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+export DIRS_STRING=$(join_by " " ${DIRS_ARRAY[@]})
+export LIBS_STRING=$(join_by " " ${LIBS_ARRAY[@]})
+export VERS_STRING=$(join_by " " ${VERS_ARRAY[@]})
+#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+# parallel is a shell tool for executing jobs in parallel.
+# OPTIONS:
+#   --no-run-if-empty: skip empty lines in input files
+#   -j $NJOBS: run a maximum of $NJOBS in parallel
+#   --joblog $JOBLOG: write logs in file $JOBLOG
+#   --linebuffer: do not postpone the stdout when
+#                 command completes
+#   --dryrun: show commands but do not run
+#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+PARALLEL="parallel --no-run-if-empty -j ${NJOBS-20} --linebuffer ${DRYRUN}"
 
 
 
@@ -138,32 +218,5 @@ done
 [[ -z $XML ]] || printf "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" > "$XML"
 [[ -z $XML ]] || printf "<evals>\n" >> "$XML"
 [[ -z $NOHEADER ]] && printf "%s,%s,%s,%s,%s,%s,%s\n" "LIB" "VER" "MAT" "MF" "MT" "OLIB" "OVER" 
-for j in $(seq 0 $(($NCHUNKS-1)))
-do
-   CHUNK=${CHUNKS[$j]}
-   CLIB=${CLIBS[$j]}
-   CVER=${CVERS[$j]}
-   NAME="$(basename $CHUNK)"
-   MAT="$(echo $NAME | cut -c1-4 | sed 's/^0*//')"
-   MF="$(echo $NAME | cut -c5-6 | sed 's/^0*//')"
-   MT="$(echo $NAME | cut -c7-9 | sed 's/^0*//')"
-   for i in $(seq 0 $(($NDIRS-1)))
-   do
-      OLD="${DIRS[$i]}/$(basename $CHUNK)"
-      if [[ -s $OLD ]]
-      then
-         [[ -z $ZIP ]] && CMD="cmp" || CMD="zcmp"
-         $CMD --silent $OLD $CHUNK && { ORIGINLIB=${LIBS[$i]}; ORIGINVER=${VERS[$i]}; break; }
-      fi
-   done
-   [[ -z $XML ]] || printf "  <section>\n" >> "$XML"
-   [[ -z $XML ]] || printf "    <mat>%s</mat>\n" $MAT >> "$XML"
-   [[ -z $XML ]] || printf "    <mf>%s</mf>\n" $MF >> "$XML"
-   [[ -z $XML ]] || printf "    <mt>%s</mt>\n" $MT >> "$XML"
-   [[ -z $XML ]] || printf "    <origin-lib>%s</origin-lib>\n" $ORIGINLIB >> "$XML"
-   [[ -z $XML ]] || printf "    <origin-ver>%s</origin-ver>\n" $ORIGINVER >> "$XML"
-   [[ -z $XML ]] || printf "  </section>\n" >> "$XML"
-   printf "%s,%s,%s,%s,%s,%s,%s\n" "$CLIB" "$CVER" "$MAT" "$MF" "$MT" "${ORIGINLIB}" "${ORIGINVER}"
-   unset ORIGINLIB ORIGINVER
-done
-[[ -z $XML ]] || printf "</evals>\n" >> "$XML"
+export -f mapping_foo
+$PARALLEL --colsep '[" "\t]+' mapping_foo {1} {2} {3} :::: "$CHUNKLIST"
