Added command line options. First test on full libraries.

diff --git a/mapping b/mapping
--- a/mapping
+++ b/mapping
@@ -18,13 +18,146 @@
 # REVISION: ---
 #===============================================================================
 
-MAT=$(echo "$FILE" | cut -c1-4)
-MF=$(echo "$FILE" | cut -c5-6)
-MT=$(echo "$FILE" | cut -c7-9)
-for dir in $(find test/* -type d)
+USAGE="Usage:
+
+$CODE  FILE  [options]
+
+
+POSITIONAL ARGUMENTS
+--------------------
+
+FILE                        input ENDF-6 file.
+
+
+KEYWORD ARGUMENTS
+-----------------
+
+-h|--help                   Print the help text.
+
+--njoy  NJOY                Set the njoy executable in relative/absolute path.
+                            (default is the NJOY2016 exe at NEA)
+
+--temp  TEMP                Set the processing temperature TEMP (in K).
+                            only one value is accepted.
+                            (default is TEMP=293.6K)
+
+--sig0  NSIG VAL1 ... VALN  Set the dilution factors.
+                            NSIG is the number of sigma0 values that follow
+                            VAL1 to VALN are NSIG sigma0 values.
+                            (default is [1E10 1E4 1E3 1E2 1E1 1E0])
+
+--prefix  PREFIX            Set the output prefix PREFIX.
+                            output files are named \"PREFIX.[extension]\".
+                            Prefix must be one word and not contain reserved characters.
+                            (default is MAT number)
+
+--covr                      Run NJOY to produce group covariance matrices.
+
+-m|--messages               Parse the NJOY output file for warnings and errors.
+                            The messages are reported in a xml file.
+
+--route  ROUTE              Replace \"route\" in the xsdir file.
+                            (default is ROUTE=0)
+
+--filename  FILENAME        Replace \"filename\" in the xsdir file.
+                            (default is FILENAME=PREFIX.ACE)
+
+--keependf                  Save ENDF-6 input in working folder with name
+                            \"PREFIX.ENDF\".
+
+--hendf                     Produce HENDF file by replacing MF3 from PENDF
+                            to ENDF.
+                            Use the merger executable from PREPRO-2017.
+"
+
+
+
+#######################################################################
+#######################################################################
+#                                                                     #
+#                    PARSE COMMAND LINE ARGUMENTS                     #
+#                                                                     #
+#######################################################################
+#######################################################################
+POSITIONAL=()
+while [[ $# -gt 0 ]]
 do
-  OLD="$dir/$FILE"
-  [[ -s $OLD ]] || continue
-  cmp --silent $OLD $FILE && { ORIGIN=$dir; break; }
+key="$1"
+case $key in
+    -h|--help) # print USAGE and exit with status 0
+    echo -e "$USAGE"
+    exit 0
+    ;;
+    *)    # unknown option
+    POSITIONAL+=("$1") # save it in an array for later
+    shift # past argument
+    ;;
+esac
 done
-printf "%s  ORIGIN  %s\n" "$FILE" "${ORIGIN:-NEW}"
+
+
+
+#######################################################################
+#######################################################################
+#                                                                     #
+#                          PROCESS INPUTS                             #
+#                                                                     #
+#######################################################################
+#######################################################################
+#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+# Get CHUNKLIST and DIRLIST from positional arguments.
+#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+msg="ERROR: missing positional arguments \"CHUNKLIST\"/\"DIRLIST\".\n$USAGE"
+[[ ${#POSITIONAL[@]} -lt 2 ]] && { >&2 echo -e "$msg"; exit 1; }
+CHUNKLIST="${POSITIONAL[0]}"
+DIRLIST="${POSITIONAL[1]}"
+#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+# Get ENDF-6 chunks from file CHUNKLIST.
+#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+if [[ -d "$CHUNKLIST" ]]
+then
+   CHUNKLIST=($(find $(realpath "$CHUNKLIST") -maxdepth 1 -type f -o -type l))
+elif [[ -s "$CHUNKLIST" ]]
+then
+   CHUNKLIST=($(cat "$CHUNKLIST"))
+else
+   >&2 echo -e "ERROR: no file or directory called '$CHUNKLIST'"; exit 1
+fi
+[[ ${#CHUNKLIST[@]} -eq 0 ]] && {>&2 echo -e "ERROR: no ENDF-6 chunk file was given.";exit 1;}
+printf '%d chunk files given\n' "${#CHUNKLIST[@]}"
+for CHUNK in ${CHUNKLIST[@]}
+do
+   [[ -s "$CHUNK" ]] || { >&2 echo -e "ERROR: empty or non-existing ENDF-6 chunk file '$CHUNK'"; exit 1; }
+done
+#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+# Get directories (DIRS) and associated keywords (KEYS).
+#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+[[ -s "$DIRLIST" ]] || { >&2 echo -e "ERROR: no file called '$DIRLIST'"; exit 1; }
+DIRS=($( awk '{print $1}' $DIRLIST ))
+KEYS=($( awk '{print $2}' $DIRLIST ))
+NDIRS=${#DIRS[@]}
+
+
+
+#######################################################################
+#######################################################################
+#                                                                     #
+#                    DO THE MAPPING                                   #
+#                                                                     #
+#######################################################################
+#######################################################################
+#MAT=$(echo "$CHUNK" | cut -c1-4)
+#MF=$(echo "$CHUNK" | cut -c5-6)
+#MT=$(echo "$CHUNK" | cut -c7-9)
+
+for CHUNK in ${CHUNKLIST[@]}
+do
+   NAME="$(basename $CHUNK)"
+   for i in $(seq 0 $(($NDIRS-1)))
+   do
+      OLD="${DIRS[$i]}/$NAME"
+      [[ -s $OLD ]] || continue 
+      cmp --silent $OLD $CHUNK && { ORIGIN=${KEYS[$i]}; break; }
+   done
+   printf "%s  ORIGIN  %s\n" "$CHUNK" "${ORIGIN:-NEW}"
+done
